keycloak:
  container_name: keycloak
  image: jboss/keycloak
  ports:
  - "8080:8080"
  volumes:
  - ./govuk/:/opt/jboss/keycloak/themes/govuk/
  - ./govuk-internal/:/opt/jboss/keycloak/themes/govuk-internal/
  - ./govuk-social-providers/:/opt/jboss/keycloak/themes/govuk-social-providers/
  environment:
    KEYCLOAK_PASSWORD: "admin"
    KEYCLOAK_USER: "admin"
    DB_VENDOR: "h2"
